-- require("vim._core.ui2").enable({
-- 	enable = true,
-- 	msg = {
-- 		targets = {
-- 			[""] = "msg",
-- 			empty = "cmd",
-- 			bufwrite = "msg",
-- 			confirm = "cmd",
-- 			emsg = "cmd",
-- 			echo = "msg",
-- 			echomsg = "msg",
-- 			echoerr = "cmd",
-- 			completion = "cmd",
-- 			list_cmd = "pager",
-- 			lua_error = "cmd",
-- 			lua_print = "msg",
-- 			progress = "pager",
-- 			rpc_error = "cmd",
-- 			quickfix = "msg",
-- 			search_cmd = "cmd",
-- 			search_count = "cmd",
-- 			shell_cmd = "pager",
-- 			shell_err = "cmd",
-- 			shell_out = "pager",
-- 			shell_ret = "msg",
-- 			undo = "msg",
-- 			verbose = "pager",
-- 			wildlist = "cmd",
-- 			wmsg = "msg",
-- 			typed_cmd = "cmd",
-- 		},
-- 		cmd = {
-- 			height = 0.5,
-- 		},
-- 		dialog = {
-- 			height = 0.5,
-- 		},
-- 		msg = {
-- 			height = 0.3,
-- 			timeout = 5000,
-- 		},
-- 		pager = {
-- 			height = 0.5,
-- 		},
-- 	},
-- })

require("config.keymaps")
require("config.options")
require("config.autocmds")
