require("kimchicoder.lspconfig")
require("kimchicoder.lspkind")
require("kimchicoder.cmp")
require("kimchicoder.lsp_installer_nvim")
require("kimchicoder.cmp")
require("kimchicoder.lspstatus")
require("kimchicoder.comments")
require("kimchicoder.gitsigns")
require("kimchicoder.trouble")
require("kimchicoder.treesitter")
require("kimchicoder.whichkey")
require("kimchicoder.project")
require("kimchicoder.lualine")
require("kimchicoder.catppuccin-config")

