require("telescope").load_extension("noice")
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = '[Telescope] find files' })
vim.keymap.set('n', '<leader>gf', builtin.git_files, { desc = '[Telescope] git find files' })
vim.keymap.set('n', '<leader>pb', builtin.grep_string, { desc = '[Telescope] grep string' })
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end) 
vim.keymap.set('n', '<leader>vpr', builtin.lsp_references, { desc = '[Telescope] find lsp references' })
vim.keymap.set('n', '<leader>km', builtin.keymaps, { desc = '[Telescope] list all known keymaps' })
