#!/usr/bin/env bash

echo "running sessionizer"
if [[ $# -eq 1 ]]; then
	selected=$1
else
	# selected=$(find ~/work/builds ~/projects ~/ ~/work ~/personal ~/personal/yt -mindepth 1 -maxdepth 1 -type d | fzf)
	selected=$(find ~/ ~/coding ~/coding/personal ~/coding/work -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
zellij_running=$(pgrep zellij)

echo $selected_name
echo "attempting to attach"

cd $selected
zellij attach $selected_name --create
exit 0
