#!/usr/bin/env bash
# Adapted from ThePrimeagen
# source: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

# If given a path, set as selected
if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/ ~/coding ~/coding/personal ~/coding/work -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
# zellij_running=$(pgrep zellij)

cd $selected
# Using default layout which runs nvim automatically on load
zellij -l $HOME/.config/zellij/layouts/default.kdl attach $selected_name --create
exit 0
